### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by ready4god2513** [DeltaSystems/Teamwork-Desk#1]
Hey Guys,

Thanks for the brilliant API wrapper for Desk.  I apologize that you weren't able to find the documentation.  The docs are relatively new and still undergoing quite a bit of work as we solidify our API.  You can find the documentation for the API here - http://developer.teamwork.com/desk/

We will be working on improving the documentation, adding live examples, etc.  If there is anything else that we can do to make your work here easier, please let me know.

**Comment by marcdiblasi** [comment]
Awesome! I feel like I mentioned in the readme maybe 1 too many times that there was no documentation that I could find. I'll go back when I have a minute and rewrite that and get some more functionality added.

Thanks for the heads up!
